/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18JfUn96SXQM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18JfUn96SXQM= >>
// ----------- >>
public class Account {
    // ----------- << attribute.annotations@AAAAAAF18JlTp98FwNw= >>
    // ----------- >>
    private int id_account;

    // ----------- << attribute.annotations@AAAAAAF18Jlwj98LVds= >>
    // ----------- >>
    private String password;

    // ----------- << attribute.annotations@AAAAAAF18Jt4Rt8e4gU= >>
    // ----------- >>
    private String email;

    // ----------- << attribute.annotations@AAAAAAF18KB/dOBYE4c= >>
    // ----------- >>
    private Set<Department>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF18KStKOGX948= >>
    // ----------- >>
    private Department ;

    // ----------- << attribute.annotations@AAAAAAF18KWkmOH9DZ8= >>
    // ----------- >>
    private Account ;

    // ----------- << attribute.annotations@AAAAAAF18KWkmOH8UeU= >>
    // ----------- >>
    private Account ;

    public int getId_account() {
        return id_account;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public Set<Department> get() {
        return ;
    }

    public Department get() {
        return ;
    }

    public Account get() {
        return ;
    }

    public Account get() {
        return ;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void set(Department ) {
        this. = ;
    }

    public void set(Account ) {
        this. = ;
    }

    public void set(Account ) {
        this. = ;
    }

    public void link(Department _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Department _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Account _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Account _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Department _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Department _, Iterator<Department> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF18JfUn96SXQM= >>
// ----------- >>
}