/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18JwBZN9gKE4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18JwBZN9gKE4= >>
// ----------- >>
public class Admin extends Account {
// ----------- << class.extras@AAAAAAF18JwBZN9gKE4= >>
// ----------- >>
}