/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18J1imd+3fdY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18J1imd+3fdY= >>
// ----------- >>
public class Department {
    // ----------- << attribute.annotations@AAAAAAF18J3Vjt/q+/k= >>
    // ----------- >>
    private String promotion;

    // ----------- << attribute.annotations@AAAAAAF18J8Vlt/0ebE= >>
    // ----------- >>
    private String year;

    // ----------- << attribute.annotations@AAAAAAF18K+ytebwcSU= >>
    // ----------- >>
    private String abbreviation;

    // ----------- << attribute.annotations@AAAAAAF18KB/dOBXju8= >>
    // ----------- >>
    private Account ;

    // ----------- << attribute.annotations@AAAAAAF18KStKOGWJBI= >>
    // ----------- >>
    private Account ;

    // ----------- << attribute.annotations@AAAAAAF18KW5FeI/ygU= >>
    // ----------- >>
    private Set<Student>  = new HashSet<>();

    public String getPromotion() {
        return promotion;
    }

    public String getYear() {
        return year;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public Account get() {
        return ;
    }

    public Account get() {
        return ;
    }

    public Set<Student> get() {
        return ;
    }

    public void setPromotion(String promotion) {
        this.promotion = promotion;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public void set(Account ) {
        this. = ;
    }

    public void set(Account ) {
        this. = ;
    }

    public void link(Account _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Account _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Student _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Student _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Student _, Iterator<Student> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF18J1imd+3fdY= >>
// ----------- >>
}