/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18LCOc+eQ9TA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18LCOc+eQ9TA= >>
// ----------- >>
public class MentoringDemand extends Post {
    // ----------- << attribute.annotations@AAAAAAF18LT+PepbMlA= >>
    // ----------- >>
    private List<Student,String> schedules;

    // ----------- << attribute.annotations@AAAAAAF18LZmveqt8UQ= >>
    // ----------- >>
    private List<Student> tutors;

    // ----------- << attribute.annotations@AAAAAAF18LatJOrSyA8= >>
    // ----------- >>
    private List<Student> students;

    public List<Student,String> getSchedules() {
        return schedules;
    }

    public List<Student> getTutors() {
        return tutors;
    }

    public List<Student> getStudents() {
        return students;
    }

    public void setSchedules(List<Student,String> schedules) {
        this.schedules = schedules;
    }

    public void setTutors(List<Student> tutors) {
        this.tutors = tutors;
    }

    public void setStudents(List<Student> students) {
        this.students = students;
    }

// ----------- << class.extras@AAAAAAF18LCOc+eQ9TA= >>
// ----------- >>
}