/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18LAuZ+dUNzo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18LAuZ+dUNzo= >>
// ----------- >>
public class Post {
    // ----------- << attribute.annotations@AAAAAAF18LQHrum9p2g= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAF18LQU7OnSVnQ= >>
    // ----------- >>
    private String name;

    // ----------- << attribute.annotations@AAAAAAF18LQu1On++7s= >>
    // ----------- >>
    private Date post_date;

    // ----------- << attribute.annotations@AAAAAAF18LSsteo4WSo= >>
    // ----------- >>
    private String content;

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Date getPost_date() {
        return post_date;
    }

    public String getContent() {
        return content;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPost_date(Date post_date) {
        this.post_date = post_date;
    }

    public void setContent(String content) {
        this.content = content;
    }

// ----------- << class.extras@AAAAAAF18LAuZ+dUNzo= >>
// ----------- >>
}