/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18Jv8Td8mfsY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18Jv8Td8mfsY= >>
// ----------- >>
public class Student extends Account {
    // ----------- << attribute.annotations@AAAAAAF18JyEZ9+gqUM= >>
    // ----------- >>
    private String firstName;

    // ----------- << attribute.annotations@AAAAAAF18JyPVt+mIUs= >>
    // ----------- >>
    private String lastName;

    // ----------- << attribute.annotations@AAAAAAF18KJ8nuDaS5Y= >>
    // ----------- >>
    private String description;

    // ----------- << attribute.annotations@AAAAAAF18KW5FeJABnQ= >>
    // ----------- >>
    private Department ;

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getDescription() {
        return description;
    }

    public Department get() {
        return ;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void set(Department ) {
        this. = ;
    }

    public void link(Department _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF18Jv8Td8mfsY= >>
// ----------- >>
}