/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package cooptool;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF18Kto5+XNrqc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF18Kto5+XNrqc= >>
// ----------- >>
public class Subject {
    // ----------- << attribute.annotations@AAAAAAF18Kz3V+ZzZEM= >>
    // ----------- >>
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

// ----------- << class.extras@AAAAAAF18Kto5+XNrqc= >>
// ----------- >>
}