@startuml
left to right direction

:student: --> (need help)
:student: --> (provide help)
:student: --> (stop participating)

(provide help) ..> (choose schedules) : << include >>
(need help) ..> (choose schedules) : << include >>
(provide help) <.. (add schedules) : << extends >>
(provide help) <.. (delete his schedules) : << extends >>
@enduml
