@startuml
left to right direction
:admin: --> (create a department)
:admin: --> (delete a department)
:student: --> (find students from a department)

(find students from a department) <.. (send a message) : << extend >>
@enduml
