@startuml
left to right direction
:student: --> (view a student account)
:student: --> (register)
:student: --> (update an account)
:student: --> (delete an account)
:admin: --> (view a student account)
:admin: --> (update an account)
:admin: --> (delete an account)
@enduml
