@startuml

title mentoring demand

state "Mentoring demand created" as mdc
state "Mentoring Demand Answered" as mda
state "Mentoring Demand Deleted" as mdd
state "Mentoring Demand Validated" as mdv
state "Mentoring Demand Supervised" as mds

state fork_state <<fork>>
state join_state <<join>>

[*] --> mdc : Create mentoring demand
mdc --> fork_state
fork_state --> mda : user registers a participation
note on link : it's forbidden to update or delete
fork_state --> mds : user realizes the mentoring session
mda --> join_state
mds --> join_state
mdc --> mdd : user deletes the mentoring demand
mdc --> mdc : user updates the mentoring demand
join_state --> mdc : everyone cancel participation
join_state --> mdv : creator validates mentoring demand
mdv --> [*]
mdd --> [*]

@enduml