@startuml

title mentoring demand

state "Mentoring demand created" as mdc
state "Mentoring Demand Answered" as mda
state "Mentoring Demand Deleted" as mdd
state "Mentoring Demand Validated" as mdv
state "Mentoring Demand Supervised" as mds

[*] --> mdc : Create mentoring demand
mdc --> mda : user registers a participation
note on link : it's forbidden to update or delete
mdc --> mds : user realizes the mentoring session
mdc --> mdd : user deletes the mentoring demand
mdc --> mdc : user updates the mentoring demand
mds --> mdc : everyone cancel participation
mda --> mdc : everyone cancel participation
mda --> mdv : creator validates mentoring demand
mdv --> [*]
mdd --> [*]

@enduml