@startuml
actor user
participant BrowsingHistoryController
participant PostFacade
participant AbstractDAOFactory
participant PostDAO
database CoopToolDatabase

user -> BrowsingHistoryController : deleteAll()
activate BrowsingHistoryController
BrowsingHistoryController -> PostFacade  : getInstance()
PostFacade -> AbstractDAOFactory : getInstance()
activate PostFacade
activate AbstractDAOFactory
AbstractDAOFactory -> AbstractDAOFactory : getPostDAO()
AbstractDAOFactory -> PostDAO : getInstance()
PostDAO --> AbstractDAOFactory : PostDAO
AbstractDAOFactory --> PostFacade : PostDAO
deactivate AbstractDAOFactory
PostFacade --> BrowsingHistoryController : PostFacade

BrowsingHistoryController -> PostFacade : deleteAllFromBrowsingHistory(user)
PostFacade -> PostDAO : deleteAllFromBrowsingHistory(user)
PostDAO -> CoopToolDatabase : saveData
deactivate BrowsingHistoryController
deactivate PostDAO

@enduml