@startuml
actor user
participant SearchStudentController
participant UserFacade
participant AbstractDAOFactory
participant UserDAO
participant User
collections ListUser
database CoopToolDatabase

user -> SearchStudentController : select department in list
user -> SearchStudentController : search()
activate SearchStudentController
SearchStudentController -> UserFacade  : getInstance()
UserFacade -> AbstractDAOFactory : getInstance()
activate UserFacade
activate AbstractDAOFactory
AbstractDAOFactory -> AbstractDAOFactory : getUserDAO()
AbstractDAOFactory -> UserDAO : getInstance()
UserDAO --> AbstractDAOFactory : UserDAO
AbstractDAOFactory --> UserFacade : UserDAO
deactivate AbstractDAOFactory
UserFacade --> SearchStudentController : UserFacade
SearchStudentController -> SearchStudentController : getDepartment()

SearchStudentController -> UserFacade : search(department : Department)
UserFacade -> UserDAO : findStudentByDepartment(department : Department)
activate UserDAO
UserDAO -> CoopToolDatabase : askForData
CoopToolDatabase --> UserDAO : result
create ListUser
UserDAO -> ListUser : new ArrayList<User>()
create User
group while result != null
    UserDAO -> User : new
    User -> ListUser : add()
end
ListUser --> UserDAO : ListUser
UserDAO --> UserFacade : ListUser
UserFacade --> SearchStudentController : ListUser
group while ListUser.hasNext()
    SearchStudentController -> SearchStudentController : listStudent.addText(ListUser.next())
end
deactivate SearchStudentController
deactivate UserFacade
deactivate UserDAO

@enduml