@startuml
actor user
participant HandleQuickHelpPostController
participant QuickHelpPostFacade
participant AbstractDAOFactory
participant QuickHelpPostDAO
participant QuickHelpPost
database CoopToolDatabase

user -> HandleQuickHelpPostController : create()
activate HandleQuickHelpPostController
HandleQuickHelpPostController -> QuickHelpPostFacade  : getInstance()
QuickHelpPostFacade -> AbstractDAOFactory : getInstance()
activate QuickHelpPostFacade
activate AbstractDAOFactory
AbstractDAOFactory -> AbstractDAOFactory : getQuickHelpPostDAO()
AbstractDAOFactory -> QuickHelpPostDAO : getInstance()
QuickHelpPostDAO --> AbstractDAOFactory : quickHelpPostDAO
AbstractDAOFactory --> QuickHelpPostFacade : quickHelpPostDAO
deactivate AbstractDAOFactory
QuickHelpPostFacade --> HandleQuickHelpPostController : QuickHelpPostFacade

HandleQuickHelpPostController -> QuickHelpPostFacade : create(description : String, subject : Subject)
create QuickHelpPost
QuickHelpPostFacade -> QuickHelpPost : new
QuickHelpPost --> QuickHelpPostFacade : QuickHelpPost
QuickHelpPostFacade -> QuickHelpPostDAO : create(quickHelpPost : QuickHelpPost)
activate QuickHelpPostDAO
QuickHelpPostDAO -> CoopToolDatabase : saveData
CoopToolDatabase --> QuickHelpPostDAO : result
alt success
    QuickHelpPostDAO --> QuickHelpPostFacade : True
    QuickHelpPostFacade --> HandleQuickHelpPostController : True
else !success
    QuickHelpPostDAO --> QuickHelpPostFacade : False
    QuickHelpPostFacade --> HandleQuickHelpPostController : False
end
deactivate HandleQuickHelpPostController
deactivate QuickHelpPostFacade
deactivate QuickHelpPostDAO

@enduml